---

- hosts: all
  become: true
  tasks:

    - name: install mlocate package
      dnf:
        name: mlocate
        state: latest
      when: ansible_distribution_version == "34" and ansible_distribution in ["Fedora", "RedHat", "CentOS"]
