- name: install apache and php
  tags: apache,httpd
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name  }}"
    state: latest

- name: install mysqld package
  tags: db_servers
  package:
    name:
      - "{{ mysql_package_name }}"
      - "{{ mysql_server_package_name }}"
    state: latest

- name: start and enable mysqld
  tags: db_servers,mysqld
  service:
    name: "{{ mysqld_service_name }}"
    state: started
    enabled: yes

- name: start and enable httpdd
  tags: apache,httpd
  service:
    name: "{{ apache_service_name  }}"
    state: started
    enabled: yes

- name: change e-mail address for admin
  tags: apache,httpd,fedora
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regex: '^ServerAdmin'
    line: ServerAdmin root@localhost
  when: ansible_distribution == "Fedora"
  notify: restart_apache

- name: copy default html file for site
  tags: apache,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: install unzip
  package:
    name: unzip

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.0.3/terraform_1.0.3_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: update server
  tags: always,fedora
  raw: /usr/bin/dnf -y upgrade
  when: ansible_distribution == "Fedora"
  changed_when: false
