---

- hosts: all
  become: true
  tasks:

    - name: install/update  mlocate and 'Web server' group packages
      dnf:
        name: 
          - mlocate
          - "@Web Server" 
        state: latest
        update_cache: yes
      when: ansible_distribution_version == "34" and ansible_distribution in ["Fedora", "RedHat", "CentOS"]
