---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (Fedora)
    tags: always,fedora
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Fedora"

  - name: update repo cache (Ubuntu)
    tags: always,ubuntu
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: demo_servers
  become: true
  tasks:

  - name: install apache and php (Ubuntu)
    tags: apache,httpd,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php (Fedora)
    tags: apache,httpd,fedora
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGs7EJCXTK/ge+3C65anCNJNMvwQJ3HXDIb6X7gsJKs1 greg default"

- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.0.3/terraform_1.0.3_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: demo_servers
  become: true
  tasks:
  
  - name: install mysqld package (Fedora)
    tags: db_servers,fedora
    dnf:
      name:
        - "community-mysql"
        - "community-mysql-server"
      state: latest
    when: ansible_distribution == "Fedora"

  - name: start and enable mysqld (Fedora)
    tags: mysqld,fedora
    service:
      name: mysqld
      state: started
      enabled: yes
    when: ansible_distribution == "Fedora"

  - name: start and enable httpdd (Fedora)
    tags: apache,httpd,fedora
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Fedora"

  - name: install mairadb package (Ubuntu)
    tags: db_servers,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: change e-mail address for admin
    tags: apache,httpd,fedora
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regex: '^ServerAdmin'
      line: ServerAdmin root@localhost
    when: ansible_distribution == "Fedora"
    register: httpd

  - name: restart httpd (Fedora)
    tags: apache,httpd,fedora
    service:
      name: httpd
      state: restarted
    when: httpd.changed 

  - name: copy default html file for site
    tags: apache,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
