---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (Fedora)
    tags: always,fedora
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Fedora"

  - name: update repo cache (Ubuntu)
    tags: always,ubuntu
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: demo_servers
  become: true
  roles:
    - demo_servers

- hosts: special
  become: true
  roles:
    - special
